name: Check DynamoDB Table

variables:
  AWS_REGION: "us-east-1"  # Change to your AWS region
  TABLE_NAME: "weatherdatatwo"
  PRIMARY_KEY: "id"
  CITY_ATTRIBUTE: "city"
  TEMP_ATTRIBUTE: "temp"


on:
  push:
    branches:
      - main  # Adjust this to your target branch\


jobs:
  check-table:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

    - name: Check if DynamoDB table exists
      run: |
        TABLE_EXISTS=$(aws dynamodb list-tables --query "TableNames[?TableName=='$TABLE_NAME']" --output text)
        if [ -z "$TABLE_EXISTS" ]; then
          echo "Table does not exist. Creating table..."
          aws dynamodb create-table \
            --attribute-definitions \
                  AttributeName=$PRIMARY_KEY,AttributeType=S \
                  AttributeName=$CITY_ATTRIBUTE,AttributeType=S \
                  AttributeName=$TEMP_ATTRIBUTE,AttributeType=N \
              --key-schema \
                  AttributeName=$PRIMARY_KEY,KeyType=HASH \
              --provisioned-throughput \
                  ReadCapacityUnits=5,WriteCapacityUnits=5 \
              --region $AWS_REGION
        else
          echo "Table already exists."
        fi
