name: Check DynamoDB Table




on:
  push:
    branches:
      - main  # Adjust this to your target branch\


jobs:
  check-table:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

    - name: Check if DynamoDB table exists
      run: |
        TABLE_NAME="weatherdatatwo"
        TABLE_EXISTS=$(aws dynamodb list-tables --query "TableNames[?TableName=='$TABLE_NAME']" --output text)
        if [ -z "$TABLE_EXISTS" ]; then
          echo "Table does not exist. Creating table..."
          aws dynamodb create-table \
            --table-name $TABLE_NAME \
            --attribute-definitions \
                  AttributeName=id,AttributeType=S \
                  AttributeName=city,AttributeType=S \
                  AttributeName=temp,AttributeType=N \
              --key-schema \
                  AttributeName=id,KeyType=HASH \
              --provisioned-throughput \
                  ReadCapacityUnits=5,WriteCapacityUnits=5 \
        else
          echo "Table already exists."
        fi
